### ISSUE TITLE
Necromancy Table Thauminomicon entry crash

### ISSUE THREAD

**Issue by nop277** [Vazkii/br101#2]
First off I'm using vanilla forge 1060 (latest recommended) and the latest 1.7.2 alpha version of the mod. I am using optifine but i turned it off and still got this error. The crash occurs when I open the necromancy table in the thauminomicon and then turn the page which results in the screen freezing and then crashing the client. I am running this in a modpack but there isn't a terrible lot of other mods involved and none that I can think would cause this. Here's the crash log: http://pastebin.com/pPtmkSRn

**Comment by Vazkii** [comment]
Wrong repository, this goes in Thaumic-Tinkerer/ThaumicTinkerer

**Comment by CatDany** [comment]
LOOOOOOOOOOOOOL
