### ISSUE TITLE
Hand is transparent

### ISSUE THREAD

**Issue by AxolotlAccount** [Vazkii/br101#5]
beta 28 latest
latest forge 1.9
vanilla forge
no optifine

with installing only psi,and when i create a world, hand texture in the first person is transparent. i think it is a render bug.
## images

with psi:

http://imgur.com/hKT609K

with no psi:

http://imgur.com/ZnAEkr0

**Comment by Vazkii** [comment]
Wrong repository. You want https://github.com/Vazkii/Psi
